name: Build Windows Exe using tar artifacts

on:
  push:
    branches: 
      - windows-fix
jobs:
  build-es-artifacts:
    name: Build Windows ES Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build Windows
      run: |
        #!/bin/bash
        PACKAGE=opendistroforelasticsearch
        cd elasticsearch/linux_distributions
        ES_VERSION=$(../bin/version-info --es)
        OD_VERSION=$(../bin/version-info --od)
        
        echo $ES_VERSION
        
          
  
