name: Build Windows Exe using tar artifacts

on:
  push:
    branches: 
      - windows-fix
jobs:
  build-es-artifacts:
    name: Build Windows ES Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build Windows
      run: |
        #!/bin/bash
        PACKAGE=opendistroforelasticsearch
        cd elasticsearch/linux_distributions
        ES_VERSION=$(../bin/version-info --es)
        OD_VERSION=$(../bin/version-info --od)
        OD_PLUGINVERSION=$OD_VERSION.0
        
        cd ../../..
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-$ES_VERSION-windows-x86_64.zip
        unzip elasticsearch-oss-$ES_VERSION-windows-x86_64.zip
        rm elasticsearch-oss-$ES_VERSION-windows-x86_64.zip
        
        #Install Plugins
        cd elasticsearch-$ES_VERSION/bin
        for plugin_path in  opendistro-sql/opendistro_sql-$OD_PLUGINVERSION.zip opendistro-alerting/opendistro_alerting-$OD_PLUGINVERSION.zip opendistro-job-scheduler/opendistro-job-scheduler-$OD_PLUGINVERSION.zip opendistro-security/opendistro_security-$OD_PLUGINVERSION.zip opendistro-index-management/opendistro_index_management-$OD_PLUGINVERSION.zip
        do
          ./elasticsearch-plugin install --batch "https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/$plugin_path"
        done
        
        cd ../..
        mv elasticsearch-$ES_VERSION $PACKAGE-$OD_VERSION
        cd $PACKAGE-$OD_VERSION
        ls -l
        
          
  
