name: Build ODFE Docker Image and Upload

on:
  push:
    branches: 
      - master
jobs:
  build-es-docker:
    name: Build ES Dcoker Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Starting ES Build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        ODFE_VER: 1.3.0
      run: |
        sudo apt-get install python-virtualenv
        work_dir=`pwd`
        echo $work_dir
        cd elasticsearch/docker
        #make build
        
        #echo "******************************"
        #echo "Login to Docker"
        #echo "******************************"
        #docker login --username $DOCKER_USER --password $DOCKER_PASS
        #docker images|grep "amazon/opendistro-for-elasticsearch" > docker_id.out
        #image_id=`awk -F' ' '{print $3}' docker_id.out`
        #echo "Docker Id is $image_id"
        #docker tag $image_id opendistroforelasticsearch/opendistroforelasticsearch:$ODFE_VER
        #docker images
        #docker push opendistroforelasticsearch/opendistroforelasticsearch:$ODFE_VER
  
  build-kibana-docker:
    needs: [build-es-docker]
    name: Build Kibana Docker
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Starting Kibana Build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          ODFE_VER: 1.3.0
        run: |
          sudo apt-get install python-virtualenv
          cd kibana/docker
          make build
          
          echo "******************************"
          echo "Uploading Kibana Docker"
          echo "******************************"
          docker login --username $DOCKER_USER --password $DOCKER_PASS
          docker images|grep "amazon/opendistro-for-elasticsearch-kibana" > kibana_id.out
          kibana_image_id=`awk -F' ' '{print $3}' kibana_id.out`
          echo "Docker Id is $kibana_image_id"
          docker tag $kibana_image_id opendistroforelasticsearch/opendistroforelasticsearch-kibana:$ODFE_VER
          docker push opendistroforelasticsearch/opendistroforelasticsearch-kibana:$ODFE_VER
        
