name: Build ODFE Docker Image and Upload

on:
  push:
    branches: 
      - actions-branch
jobs:
  install-docker:
    name: Build ES Dcoker Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Print present working directory
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        ODFE_VER: 1.3.0
      run: |
        sudo apt-get install python-virtualenv
        work_dir=`pwd`
        echo $work_dir
        cd elasticsearch/docker
        make build
        
        echo "******************************"
        echo "Login to Docker"
        echo "******************************"
        docker login --username mayhem6788 --password $DOCKER_PASS
        docker images|grep "amazon/opendistro-for-elasticsearch" > docker_id.out
        image_id=`awk -F' ' '{print $3}' docker_id.out`
        echo "Docker Id is $image_id"
        docker tag $image_id mayhem6788/opendistro-for-elasticsearch:$ODFE_VER
        docker images
        docker push mayhem6788/opendistro-for-elasticsearch:$ODFE_VER
        
        
