name: CI

on:
  push:
    branches: 
      - actions-branch
jobs:
  build:
    name: Create Docker Conrainer
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Print present working directory
      run: |
        work_dir=`pwd`
        echo $work_dir
