name: CI

on:
  push:
    branches: 
      - actions-branch
jobs:
  install-docker:
    name: Install Docker in MacOs and Build Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Print present working directory
      run: |
        sudo apt-get install python-virtualenv
        work_dir=`pwd`
        echo $work_dir
        cd elasticsearch/docker
        sudo make build
