name: Sign Debian

on:
  push:
    branches: 
      - actions-branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sign deb
      env:
        PGP_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC_KEY }}
        PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      run: |
        echo `pwd`
        echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list.d/aptly.list
        sudo apt-get install gnupg1
        sudo apt install gpgv1
        alias gpg=gpg1
        sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
        #sudo apt-get update
        #sudo apt-get install aptly
        
        #mkdir -p downloads/debs
        #aws s3 sync s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs downloads/debs
        #ls -ltr downloads/debs/
        #aptly repo create -distribution=stable -component=main odfe-release
        #aptly repo list
        #aptly repo add odfe-release downloads
        #aptly repo show -with-packages odfe-release
        #aptly snapshot create opendistroforelasticsearch-1.3.0 from repo odfe-release
        #aptly snapshot list
        gpg1 --import $PGP_PUBLIC_KEY
        gpg1 --allow-secret-key-import --import $PGP_PRIVATE_KEY
        #aptly publish snapshot opendistroforelasticsearch-1.3.0
        #aws s3 sync ~/.aptly/public/ s3://artifacts.opendistroforelasticsearch.amazon.com/staging/apt
        #aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 —paths "/staging/apt/*"
